### ISSUE TITLE
Aseprite Translation Manager

### ISSUE THREAD

**Issue by ghost** [Inky1003/aseprite-em-portugues#1]
Hi to all translators of Aseprite!

I wrote a program "Aseprite Translation Manager" that can scan your translation INI file (any language) by comparing it to Aseprite’s en.ini file (in folder \data\strings).

Download the program and manual here to scan your own translation INI file in a very easy way and keep it up to date with latest Aseprite version.

https://github.com/pixelartgirl/Aseprite-Translation-Manager

PixelArtGirl

**Comment by pauromateusu** [comment]
Not an issue, closing.

btw I don't use windows, I can't use that, sorry.

**Comment by ghost** [comment]
It should be possible to run it with Wine: https://www.winehq.org/

**Comment by pauromateusu** [comment]
I mean, I could use, but I have no Aseprite. It was my friend's and I decided to help with his .ini files, as another friend bought him Aseprite and he don't know english. Sadly, today we're no longer friends, and I can't buy Aseprite. 

I've also heard of LibreSprite, which could be an option, but then I gave up as It doesn't have a translations system.

Also, I'd thank If any brazilian or portuguese folk could continue this project, because I'm not anymore interested in translating this. I believe there should be anyone who wants to contribute and continue...
